package ac.daffodil.amirul.ui.view.admin.debitvoucher;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Button;
import ac.daffodil.amirul.ui.view.admin.ledger.GroupComboBox2;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class DebitViewDesign3 extends VerticalLayout {
    protected VerticalLayout form;
    protected TextField ledgerName;
    protected TextField ledgerCode;
    protected GroupComboBox2 ledgerGroup;
    protected TextField openingBalance;
    protected TextField debitBalance;
    protected TextField creditBalance;
    protected Button update;
    protected Button cancel;
    protected Button delete;

    public DebitViewDesign3() {
        Design.read(this);
    }
}
