package ac.daffodil.amirul.ui.view.admin.debitvoucher;

import ac.daffodil.amirul.ui.view.admin.debitvoucher.LedgerComboBox;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.DateField;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class DebitEditViewDesign2 extends VerticalLayout {
	protected HorizontalLayout reportHeader;
	protected Label orderId;
	protected Label stateLabel;
	protected DateField date;
	protected Label voucherLabel;
	protected TextField voucherNo;
	protected Label lblDebitedAccount;
	protected LedgerComboBox accountToBeDebited;
	protected Label lblDebitedAmount1;
	protected TextField txtDebitedAmount1;
	protected Label lblCreditedAccount;
	protected LedgerComboBox accountToBeCredited;
	protected Label lblCreditedAmount;
	protected TextField txtCreditedAmount;
	protected Label lblNarration;
	protected TextArea txtNarration;
	protected Button cancel;
	protected Button ok;
	protected VerticalLayout form;
	protected TextField ledgerName;
	protected TextField ledgerCode;
	protected TextField openingBalance;
	protected TextField debitBalance;
	protected TextField creditBalance;
	protected Button update;
	protected Button cancel1;
	protected Button delete;

	public DebitEditViewDesign2() {
		Design.read(this);
	}
}
