package ac.daffodil.amirul.ui.view.admin.creditvoucher;

import ac.daffodil.amirul.ui.view.admin.debitvoucher.LedgerComboBox;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.DateField;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class CreditEditViewDesign extends VerticalLayout {
	protected HorizontalLayout reportHeader;
	protected Label orderId;
	protected Label stateLabel;
	protected DateField date;
	protected Label voucherLabel;
	protected TextField voucherNo;
	protected Label lblCreditedAccount1;
	protected LedgerComboBox accountToBeCredited;
	protected Label lblDebitedAmount1;
	protected TextField txtCreditedAmount;
	protected Label lblDebitedAccount;
	protected LedgerComboBox accountToBeDebited;
	protected Label lblCreditedAmount;
	protected TextField txtDebitedAmount;
	protected Label lblNarration;
	protected TextArea txtNarration;
	protected Button cancel;
	protected Button add;

	public CreditEditViewDesign() {
		Design.read(this);
	}
}
